name: Java Maintainability Analysis

on:
  # Analyze default branch
  push:
    branches: [ main ]
  
  # Run on PRs targeting main branch
  pull_request:
    branches: [ main ]
    types: [ labeled ]
  
  # Allow manual triggers
  workflow_dispatch:
    inputs:
      label:
        description: 'Label for this maintainability run'
        required: true
        default: 'manual-run'

permissions:
  contents: read
  security-events: write
  actions: read

jobs:
  maintainability-check:
    # Only run if triggered manually or if PR is labeled with 'maintainability'
    if: ${{ github.event_name == 'workflow_dispatch' || github.event_name == 'push' || contains(github.event.pull_request.labels.*.name, 'maintainability') }}
    name: CodeQL Maintainability Analysis
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      # Initialize CodeQL
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: java
          queries: +security-and-quality
          config-file: ./.github/codeql/codeql-config.yml

      # Autobuild attempts to build any compiled languages
      - name: Autobuild
        uses: github/codeql-action/autobuild@v3

      # Run the CodeQL analysis
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
        with:
          category: "java-maintainability"