name: Build, Test and Release

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Allow manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Needed for creating releases
      
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    
    - name: Extract version from pom.xml
      id: get_version
      run: |
        VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
        echo "VERSION=$VERSION" >> $GITHUB_ENV
    
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    
    - name: Run tests
      run: mvn -B test
      
    - name: Verify JAR exists
      run: |
        if [ ! -f target/owasp-scanner.jar ]; then
          echo "ERROR: JAR file not found at target/owasp-scanner.jar"
          exit 1
        fi
        echo "JAR file found and ready for release"
        ls -la target/
    
    - name: Create Release
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v${{ env.VERSION }}-${{ github.run_number }}
        name: OWASP Scanner v${{ env.VERSION }} (Build ${{ github.run_number }})
        draft: false
        prerelease: false
        files: target/owasp-scanner.jar
        body: |
          OWASP Scanner v${{ env.VERSION }} (Build ${{ github.run_number }})
          
          ## How to use
          
          ```bash
          java -jar owasp-scanner.jar scan /path/to/your/code
          ```
          
          ## Changes in this build
          - Automated build from latest code in main branch
          - Build created on: ${{ github.event.repository.updated_at }}
