name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Allow manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Required for the release creation step

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    
    - name: Extract version from pom.xml
      id: get_version
      run: |
        VERSION=$(grep -m 1 "<version>" pom.xml | sed -n 's/.*<version>\(.*\)<\/version>.*/\1/p')
        echo "VERSION=$VERSION" >> $GITHUB_ENV
        echo "VERSION=$VERSION"
    
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    
    - name: Run tests
      run: mvn -B test
    
    - name: Create Release
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      id: create_release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        # Verify JAR file exists
        if [ ! -f "target/owasp-scanner.jar" ]; then
          echo "JAR file not found at expected location"
          exit 1
        fi
        
        # Create tag name
        TAG_NAME="v${{ env.VERSION }}-${{ github.run_number }}"
        
        # Create release with GitHub CLI
        gh release create "$TAG_NAME" \
          --title "OWASP Scanner $TAG_NAME" \
          --notes "OWASP Scanner v${{ env.VERSION }} build ${{ github.run_number }}

        ## How to use

        \`\`\`bash
        java -jar owasp-scanner.jar scan /path/to/your/code
        \`\`\`

        ## Changelog
        - Improved security scanning for .NET applications
        - Bug fixes and performance improvements" \
          "./target/owasp-scanner.jar"
