# This workflow has been replaced by separate workflows:
# - unit-tests.yml: Runs unit tests
# - integration-tests.yml: Runs integration tests
# - release.yml: Builds and creates releases after verifying tests

name: DEPRECATED - Please use the new workflows
on:
  workflow_dispatch:

jobs:
  notice:
    runs-on: ubuntu-latest
    steps:
      - name: Notice
        run: |
          echo "This workflow is deprecated."
          echo "Please use the new workflows instead."
          exit 1
