name: Build and Release

on:
  push:
    branches: [ main ]
    tags:
      - 'v*.*.*'
  workflow_dispatch:  # Allow manual trigger

jobs:
  unit-tests:
    uses: ./.github/workflows/unit-tests.yml

  integration-tests:
    uses: ./.github/workflows/integration-tests.yml

  build-and-release:
    needs: [unit-tests, integration-tests]
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Required for release creation
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    
    - name: Extract version from pom.xml
      id: get_version
      run: |
        VERSION=$(grep -m 1 "<version>" pom.xml | sed -n 's/.*<version>\(.*\)<\/version>.*/\1/p')
        echo "VERSION=$VERSION" >> $GITHUB_ENV
        echo "VERSION=$VERSION"
    
    - name: Build with Maven
      run: mvn -B package --file pom.xml -DskipTests
    
    - name: Create Release
      if: github.event_name == 'push' && (startsWith(github.ref, 'refs/tags/v') || github.ref == 'refs/heads/main')
      id: create_release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        # Verify JAR file exists
        if [ ! -f "target/owasp-scanner.jar" ]; then
          echo "JAR file not found at expected location"
          exit 1
        fi
        
        # Create tag name based on either existing tag or version+run number
        if [[ "${{ github.ref }}" == refs/tags/* ]]; then
          TAG_NAME="${{ github.ref_name }}"
        else
          TAG_NAME="v${{ env.VERSION }}-${{ github.run_number }}"
        fi
        
        # Create release with GitHub CLI
        gh release create "$TAG_NAME" \
          --title "OWASP Scanner $TAG_NAME" \
          --notes "OWASP Scanner $TAG_NAME

        ## How to use

        ```bash
        java -jar owasp-scanner.jar scan /path/to/your/code
        ```

        ## Changelog
        - Improved security scanning capabilities
        - Enhanced .NET application scanning
        - Updated test framework to support parameterized tests
        - Code quality improvements" \
          "./target/owasp-scanner.jar"
