name: Unit Tests

on:
  workflow_call:
    inputs:
      java-version:
        description: 'Java version to use'
        required: false
        default: '21'
        type: string

permissions:
  contents: read

jobs:
  run-tests:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: ${{ inputs.java-version }}
        distribution: 'temurin'
        cache: 'maven'
    
    - name: Run unit tests
      run: mvn clean test
    
    - name: Upload test reports
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: test-reports
        path: target/surefire-reports
        retention-days: 5
