name: Unit Tests

on:
  workflow_call:
    inputs:
      java-version:
        description: 'Java version to use'
        required: false
        default: '21'
        type: string
    outputs:
      test-reports:
        description: 'Path to test reports'
        value: ${{ jobs.run-tests.outputs.test-reports }}

jobs:
  run-tests:
    runs-on: ubuntu-latest
    outputs:
      test-reports: ${{ steps.upload-reports.outputs.artifact-id }}
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: ${{ inputs.java-version }}
        distribution: 'temurin'
        cache: 'maven'
    
    - name: Run unit tests
      run: mvn clean test
    
    - name: Upload test reports
      if: failure()
      uses: actions/upload-artifact@v3
      id: upload-reports
      with:
        name: test-reports
        path: target/surefire-reports
        retention-days: 5
